apiVersion: v1  
kind: Service  
metadata:  
  name: real-ip-svc  
spec:  
  selector:  
    app: kestrelli-real-ip  
  ports:  
    - protocol: TCP  
      port: 80        # 外部访问端口  
      targetPort: 5000  # 映射到Flask的5000端口  
  type: NodePort      # 非直连模式必需  