apiVersion: apps/v1
kind: Deployment
metadata:
  # 修改工作负载名称，可换成自设
  name: kestrelli-real-ip     
  # 增加命名空间
  namespace: kestrelli             
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kestrelli-real-ip          # 注意：selector 的标签也要同步修改，以匹配 template 中的标签
  template:
    metadata:
      labels:
        app: kestrelli-real-ip      # 修改 Pod 的标签，与 selector 保持一致
    spec:
      containers:
      - name: flask
        image: test-angel01.tencentcloudcr.com/kestrelli/kestrel-seven-real-ip:v1.0
        ports:
        - containerPort: 5000